### ISSUE TITLE
"VM_SGB_TRANSFER" example uses "&lt;" instead of "<" symbol

### ISSUE THREAD

**Issue by HeyItsLollie** [chrismaltby/gb-studio-docs#29] opened 2024-06-21 00:53 UTC
https://www.gbstudio.dev/docs/scripting/gbvm/gbvm-operations/#vm_sgb_transfer

```
VM_SGB_TRANSFER  
.db ((0x04 &lt;&lt; 3) | 1), 1, 0x07, ((0x01 &lt;&lt; 4) | (0x02 &lt;&lt; 2) | 0x03), 5,5, 10,10,  0, 0, 0, 0, 0, 0, 0, 0 ; ATTR_BLK packet
```

This example incorrectly uses the HTML Unicode entry `&lt;` instead of the `<` symbol. It should read:

```
VM_SGB_TRANSFER  
.db ((0x04 << 3) | 1), 1, 0x07, ((0x01 << 4) | (0x02 << 2) | 0x03), 5,5, 10,10,  0, 0, 0, 0, 0, 0, 0, 0 ; ATTR_BLK packet
```

**Comment by chrismaltby** [comment] 2024-07-16 10:19
Thanks @HeyItsLollie I've updated my script that pulls this text from the GB Studio repo and autogenerates that file, I just needed to make it not escape characters used within markdown code blocks. I've regenerated the docs and the issue is fixed now.

**Closed as completed by chrismaltby** 2024-07-16 10:19 UTC
